service: auth-server

frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    port: 4000
  webpack:
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:${env:ENV}, 'dev'}
  region: us-east-1

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    timeout: 30
